name: example
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  j2d: 
    path: ../packages/j2d
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
dependencies:
  json_annotation: ^4.6.0
