name: j2d
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  build: ^2.3.0
  path: ^1.8.2
  recase: ^4.0.0
  source_gen: ^1.2.2
  code_builder: ^4.2.0
  dart_style: ^2.2.3
  tuple: ^2.0.0

dev_dependencies:
  build_config: ^1.1.0
  lints: ^2.0.0
  test: ^1.16.0
